# Generated by Django 5.2.7 on 2026-01-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
