# Generated by Django 5.2.7 on 2026-01-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations_visit', '0002_alter_timeslot_end_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
