# Generated by Django 5.2.7 on 2026-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patients', 'Patient'), ('admin', 'Admin')], max_length=20),
        ),
    ]
