# Generated by Django 5.2.7 on 2026-01-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_table'),
        ('user', '0005_alter_user_role'),
    ]

    operations = [
    ]
