# Generated by Django 5.2.7 on 2026-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20260126_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
