# Generated by Django 5.2.7 on 2026-02-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_specialization'),
        ('user', '0007_alter_user_specialization'),
    ]

    operations = [
    ]
